sonar.organization=napoleon0sam
sonar.projectKey=Napoleon0sam_quality-scan-orchestrator
sonar.projectName=quality-scan-orchestrator

sonar.sources=src,scripts
sonar.tests=tests
sonar.python.version=3.12

sonar.exclusions=reports/**,.venv/**,**/__pycache__/**
